### ISSUE TITLE
Generate Node stream

### ISSUE THREAD

**Issue by AlexanderKulia** [singerla/pptx-automizer#49]
Hi. Is there a way to generate a Node stream from an Automizer instance? For my project we want to direct output to stdout instead of creating a file

**Comment by singerla** [comment]
Hi! This sounds useful. Please take a look at `feature-output-stream` branch:

```ts
const stream = await automizer
  .addSlide('ChartBarsStacked.pptx', 1, (slide) => {
    // slide.addElement('SlideWithImages.pptx', 2, 'imageJPG');
  })
  // ...
  .stream();  // use .stream() instead of .write(location)

stream.pipe(process.stdout)  // output current pptx archive to stdout
```

I hope it helps! :)

**Comment by AlexanderKulia** [comment]
Very cool, this should fit our use case perfectly.

I see that JSZip options are [hardcoded](https://github.com/singerla/pptx-automizer/blob/feature-output-stream/src/helper/archive/archive.ts#L10) which is not a problem for us, we use `nodebuffer` anyway, but maybe it would make sense to expose JSZip.JSZipGeneratorOptions in `.stream()`?

**Comment by singerla** [comment]
I added your suggestions to the library. Use it like this:

```ts
// It is also possible to get a ReadableStream. 
// stream() accepts JSZip.JSZipGeneratorOptions for 'nodebuffer' type. 
const stream = await pres.stream({
  compressionOptions: {
    level: 9,
  },
})
// You can e.g. output the pptx archive to stdout instead of writing a file:
stream.pipe(process.stdout)

// If you need any other output format, you can eventually access 
// the underlying JSZip instance:
const finalJSZip = await pres.getJSZip()
// Convert the output to whatever needed:
const base64 = await finalJSZip.generateAsync({ type: 'base64' })
```

Thank you very much again for your participation! :rocket:

**Comment by tonitakala** [comment]
@singerla has this change been published to npm? I just started using the package so I am not aware of the background of the change.

It seems like the current release (0.2.1) does not include for example pres.getJSZip() looking at the dist code: https://www.npmjs.com/package/pptx-automizer?activeTab=code

Also it seems like `lodash` dependency is removed at some point, but with current release (0.2.1) the simple example code gives an error about missing module `lodash`. I can make a new issue about this, but it may be also fixed by updating npm release.
